### ISSUE TITLE
Improve configuration

### ISSUE THREAD

**Issue by evillemez** [AmericanCouncils/WebServicesBundle#2]
Config format should change to follow the model of nelmio cors.

The current format is:

```
ac_web_services:
    include_dev_exceptions: true
    include_response_data: true
    allow_code_suppression: true
    default_response_format: json
    api_paths: 
        - "{^/api/}"
```

Future format should include a `defaults` section and a `paths` section that allow overriding the defaults.

Also, `Resources/config/config.yml` should be automatically imported, instead of having to do it manually.
